OFDM:
  Pilotnum: 32
  SNRdb: 12
  mode: 0
log:
  log_prefix: fix_H
  print_freq: 1
  val_freq: 20
model:
  h_dim: 512
  in_dim: 1024
  n_blocks: 2
  out_dim: 128
train:
  batch_size: 1024
  lr: 0.002
  lr_decay: 0
  optimizer: adam
  val_batch_size: 10000
