# config for full runner
model: resnet34
cnnmodel: base # base or resnet34 or resnet50
Pn: 32
mode: 0
use_yp: True
batch_size: 500
FC:
  in_dim: 1024
  h_dim: 4096
  out_dim: 2048
  n_blocks: 2
resume: 1122-20-57-33
run_mode: validation  # validation or testing
