# config for full runner

RE: # Route Estimator
  h_dims: [512, 512, 256]
  in_dim: 1024
  out_dim: 256
  act: sigmoid
  Hdom: time
  Pilotnum: 32
ckpt:
  redir: /data/siyu/NAIC/Submit/checkpoints/Route # path to checkpoint files of route estimator
  medir: /data/siyu/NAIC/Submit/checkpoints/Mode # path to checkpoint files of mode estimator
log:
  run_mode: validation