# config for full runner
cnnmodel: base # base or resnet34 or resnet50
Pn: 8
mode: 0
FC:
  in_dim: 1024
  h_dim: 4096
  out_dim: 2048
  n_blocks: 2
resume: 1118-01-07-26
run_mode: validation  # validation or testing