# config for full runner

RE: # Route Estimator
  h_dims: [512, 512, 256]
  in_dim: 1024
  out_dim: 256
  act: sigmoid
  Hdom: time
  Pilotnum: 32
ckpt:
  redir: /data/siyu/NAIC/workspace/Y2HEstimator/TEST # path to checkpoint files of route estimator
  mmedir: /data/siyu/NAIC/workspace/ModeEstimator/TEST # path to checkpoint files of mode estimator