# config for full runner
ME:
  out_dim: 2
RE: # Route Estimator
  model: CNN # CNN or MLP
  # for CNN model
  in_nc: 2
  numblocks: [2,2,2,2]
  h_dims: [512, 512, 256]
  in_dim: 1024
  out_dim: 256
  act: sigmoid
  Hdom: time
  Pilotnum: 32
ckpt:
  models: [cnn, resnet, cnn]
  redir: [1112-12-59-18, 1113-16-57-39, 1114-23-39-47] # path to checkpoint files of route estimators 
  # medir: /data/siyu/NAIC/Submit2/checkpoints/Mode # path to checkpoint files of mode estimator
log:
  run_mode: validation  # validation or testing