mode: 0
Pn: 8
model: none # this will be set by args
cnnmodel: base # base (use resnet18 as CNN) or resnet34.
n_epochs: 300
print_freq: 100
save_freq: 10
lr_decay: 50
lr_threshold: 0.00001
train:
  lr: 0.0001
  train_batch_size: 512 # 256 for resnet34, 512 for base
  val_batch_size: 1000
  CNN_resume: BestResnet18 
  optimizer: adam
FC:
  in_dim: 1024
  h_dim: 4096
  out_dim: 2048
  n_blocks: 2