mode: 0
Pn: 8
model: cnn
cnnmodel: base
use_yp: True
n_epochs: 300
print_freq: 100
lr_decay: 30
lr_threshold: 0.00001
train:
  cnn_lr: 0.0003
  fc_lr: 0.0001
  train_batch_size: 256 # 256 for resnet34, 512 for base
  val_batch_size: 2000
  FC_resume: 1118-00-36-40 # 1118-15-33-37 for Pn 32 1118-00-36-40 for Pn 8
  CNN_resume: None # 1118-01-07-26
  freeze_FC: True
  optimizer: adam
FC:
  in_dim: 1024
  h_dim: 4096
  out_dim: 2048
  n_blocks: 2