OFDM:
  Pilotnum: 8
  SNRdb: -1  # -1 mean random SNR
  mode: -1
log:
  print_freq: 100
  val_freq: 1
  save_freq: -1
model:
  h_dims: [512, 256, 64]
  in_dim: 1024
  out_dim: 2
  act: sigmoid
  Hdom: time
train:
  batch_size: 1024
  lr: 0.002
  lr_decay: 0
  optimizer: adam
  random: 1 # whether to use random generated dataset.
  val_batch_size: 100
  n_epochs: 30