OFDM:
  Pilotnum: -1
  SNRdb: -1
  mode: 0
log:
  print_freq: 100
  val_freq: 20
  save_freq: 1
model:
  in_ch: 4
  out_ch: 2
  numblocks: [2,2,2,2]
train:
  batch_size: 512
  lr: 0.02
  lr_decay: 0
  optimizer: adam
  random: 0
  val_batch_size: 1000
  n_epochs: 100
